cari/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$', index, name='index'),
]

linkensphere/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import profile.urls as profile
from profile.views import index as index_profile
from django.views.generic import TemplateView
import riwayat.urls as riwayat
import user_auth.urls as user_auth
import status_page.urls as status_page
import cari.urls as cari


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^profile/status/', include(status_page, namespace='status_page')),
    url(r'^$', TemplateView.as_view(template_name='landingPage.html'),name='landingpage'),
    url(r'^$', RedirectView.as_view(url='/profile/', permanent=True), name='index'),
    url(r'^riwayat/', include(riwayat, namespace='riwayat')),
    url(r'^user_auth/', include(user_auth, namespace='user_auth')),
	url(r'^profile/teman/', include(cari, namespace='cari'))

]
#url

profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile, update_profile, edit_profile_local, delete_skill


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit/', edit_profile, name='edit-profile'),
    url(r'^update-profile/$', update_profile, name='update-profile'),
    url(r'^edit-profile-local/$', edit_profile_local, name='edit-profile-local'),
    url(r'^delete-skill/(?P<skillname>[a-zA-Z]+)$', delete_skill, name='delete-skill')

]

user_auth/urls.py
from django.conf.urls import url
from .views import *

from custom_auth import auth_login, auth_logout

urlpatterns = [
    # custom auth
    url(r'^login/$', auth_login, name='auth_login'),
    url(r'^logout/$', auth_logout, name='auth_logout'),
    url(r'^$', index, name='index'),

]

profile/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length=100)
    birthday = models.DateField()
    gender = models.CharField(max_length=10)
    expert = models.CharField(max_length=100)
    description = models.TextField()
    email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add = True)

profile/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import *
from django.http import QueryDict
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from user_auth.views import authenticate
from utils import *
from user_auth.models import Pengguna, Status, Keahlian
from django.urls import reverse

response = {}
def index(request): # pragma: no cover
    if not authenticate(request):
        return HttpResponseRedirect(reverse('user_auth:index'))
    else:
        kode_identitas = get_data_user(request, 'kode_identitas')
        user_exist = check_user_in_database(request, kode_identitas)
        if (user_exist):
            pengguna = Pengguna.objects.get(npm = kode_identitas)
        else:
            pengguna = create_new_user(request)
        response['user'] = pengguna
        if Status.objects.filter(pengguna=pengguna).count() > 0:
            latest_status = Status.objects.filter(pengguna=pengguna).latest('created_date')
            response['latest_status'] = latest_status
            status_count = Status.objects.filter(pengguna=pengguna).count()
            response['status_count'] = status_count
        html = 'profile/profile.html'
        response['menuSelected'] = 'profile'
        return render(request, html, response)

def edit_profile(request): # pragma: no cover
    if not authenticate(request):
        return HttpResponseRedirect(reverse('user_auth:index'))
    else:
        kode_identitas = get_data_user(request, 'kode_identitas')
        pengguna = Pengguna.objects.get(npm = kode_identitas)
        if Status.objects.filter(pengguna=pengguna).count() > 0:
            latest_status = Status.objects.filter(pengguna=pengguna).latest('created_date')
            response['latest_status'] = latest_status
            status_count = Status.objects.filter(pengguna=pengguna).count()
            response['status_count'] = status_count
        response['user'] = pengguna
        skill = Keahlian.objects.filter(pengguna=pengguna)
        response['skill'] = skill
        response['connected'] = check_user_connected_linkedin(request, kode_identitas)
        html = 'profile/edit.html'
        return render(request, html, response)

@csrf_exempt
def update_profile(request): # pragma: no cover
    if request.method == 'POST':
        kode_identitas = get_data_user(request, 'kode_identitas')
        pengguna = Pengguna.objects.get(npm = kode_identitas)
        fullname = request.POST['full_name']
        url_linkedin = request.POST['url_linkedin']
        picture_url = request.POST['picture_url']
        email = request.POST['email']
        headline = request.POST['headline']
        pengguna.nama = fullname
        pengguna.url_linkedin = url_linkedin
        pengguna.foto = picture_url
        pengguna.email = email
        pengguna.headline = headline
        pengguna.save()
        return HttpResponseRedirect(reverse('profile:edit-profile'))
@csrf_exempt
def edit_profile_local(request): # pragma: no cover
    if request.method == 'POST':
        request.POST = request.POST.copy()
        show = request.POST['show_score']
        keahlian = request.POST.getlist('skill')
        level = request.POST.getlist('level')
        kode_identitas = get_data_user(request, 'kode_identitas')
        pengguna = Pengguna.objects.get(npm = kode_identitas)
        counter = 0;
        for a in keahlian:
            if (Keahlian.objects.filter(pengguna=pengguna,keahlian=a)):
                keahlianObj = Keahlian.objects.get(pengguna=pengguna,keahlian=a)
                keahlianObj.keahlian = a
                keahlianObj.level = level[counter]
            else:
                keahlianObj = Keahlian.objects.create(pengguna=pengguna, keahlian=a,level=level[counter])
            keahlianObj.save()
            counter += 1
        pengguna.show_score = show
        pengguna.save()
    return HttpResponseRedirect(reverse('profile:edit-profile'))

def delete_skill(request,skillname):# pragma: no cover
    print('=====>delete')
    if request.method == 'GET':
        kode_identitas = get_data_user(request, 'kode_identitas')
        pengguna = Pengguna.objects.get(npm = kode_identitas)
        Keahlian.objects.get(pengguna=pengguna,keahlian = skillname).delete()
        return HttpResponseRedirect(reverse('profile:edit-profile-local'))

# Birthday
# Gender
# Expertise : list
# Description
# Email

profile/templates/profile/edit.html
{% extends "basic.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<div class="profile">
  <div class="profilePic">
    <img class="photo" src="{{ user.foto }}">
  </div>
  <script type="in/Login"></script>
  <div class="containerContent">
    <div class="content">
      <p><b>Nama: </b><span id="fullName">{{ user.nama }}</span></p>
      <p><b>NPM: </b>{{ user.npm }}</p>
      <p><b>Keahlian: </b>{% for ii in split_expertise %} <span class="expert">{{ ii }}</span> {% endfor %}</p>
      <p><b>Email: </b>{{ user.email }}</p>
      <p><b>Profile LinkedIn: </b><span id="profileUrl"><a href="{{ user.url_linkedin }}">{{ user.url_linkedin }}</a></span></p>
      <form action="{% url 'profile:edit-profile-local' %}" method="POST">
          {% csrf_token %}
          <p><b>Tunjukkan Nilai: </b>
            Ya <input type="radio" name="show_score" value="True" {% if user.show_score == True %} checked{% endif %}>
            Tidak <input type="radio" name="show_score" value="False" {% if user.show_score == False %} checked{% endif %}>
          </p>
        <div class="appendSkill">
        {% if skill %}
          {% for s in skill %}
          <div class="skillChooserContainer">
            <div>
              <h2>Keahlian</h2>
              <select name="skill">
                <option value="ja" {% if s.keahlian == 'ja' %} selected{% endif %}>Java</option>
                <option value="py" {% if s.keahlian == 'py' %} selected{% endif %}>Python</option>
                <option value="c" {% if s.keahlian == 'c' %} selected{% endif %}>C#</option>
                <option value="ko" {% if s.keahlian == 'ko' %} selected{% endif %}>Kotlin</option>
              </select>
            </div>
            <div>
              <h2>Level</h2>
              <select name="level">
                <option value="be" {% if s.level == 'be' %} selected{% endif %}>Beginner</option>
                <option value="in" {% if s.level == 'in' %} selected{% endif %}>Intermediate</option>
                <option value="ex" {% if s.level == 'ex' %} selected{% endif %}>Expert</option>
                <option value="le" {% if s.level == 'le' %} selected{% endif %}>Legend</option>
              </select>
            </div>
            <div>
              <a href="{% url 'profile:delete-skill' s.keahlian %}"><div style="margin-top:2em;border-radius:50%;font-family: 'Open Sans';color:red;border: 1px solid red;">X</div></a>
            </div>
          </div>
          {% endfor %}
        {% endif %}
        </div>
        <button onclick="addSkill()">Add Skill</button>
        <div class="editProfileButtonContainer">
          <input type="submit" class="editProfileButton">
            <a onclick="logOutFromLinkedin();" class="editProfileButton">Logout</a>
        </div>
      </form>
    </div>
  </div>
</div>
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous">
</script> 
<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key: 816fkc7lpz0883
    onLoad: onLinkedInLoad
    authorize: true
    lang: 
</script>
<script type="text/javascript">
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    // Handle the successful return from the API call
    function onSuccess(data) {
        console.log(data);
        const fullName = data.firstName+" "+data.lastName;
        const profileUrl = data.publicProfileUrl;
        updateProfile(data);
    }

    function updateProfile(data) {
      $.ajax({
        method : 'POST',
        url : "{% url 'profile:update-profile' %}",
        data : {
          'full_name' : data.firstName+" "+data.lastName,
          'url_linkedin': data.publicProfileUrl,
          'picture_url': data.pictureUrl,
          'email': data.emailAddress,
          'headline': data.headline,
        },
        dataType : 'json',
        success : function(response) {
          window.location = '/profile';
        },
        error : function(error) {
          console.log(error);
        }
      });
    }

    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }

    // Use the API call wrapper to request the member's basic profile data
    function getProfileData() {
        IN.API.Raw("/people/~:(first-name,last-name,headline,email-address,picture-url,public-profile-url)").result(onSuccess).error(onError);
    }

    function logOutFromLinkedin() {
      IN.User.logout(logOut);
    }

    function logOut() {
      $.ajax({
        method : 'POST',
        url : "{% url 'user_auth:auth_logout' %}",
        success : function(response) {
          window.location.reload();
        },
        error : function(error) {
          console.log(error);
        }
      });
    }

    function addSkill() {
      html = '<div class="skillChooserContainer"><div><h2>Keahlian</h2><select name="skill"><option value="ja">Java</option><option value="py">Python</option><option value="c">C#</option><option value="ko">Kotlin</option></select></div><div><h2>Level</h2><select name="level"><option value="be">Beginner</option><option value="in">Intermediate</option><option value="ex">Expert</option><option value="le">Legend</option></select></div></div></div>'
      $('.appendSkill').append(html);   
      event.preventDefault()
    }
   
</script>
{% endblock %}

profile/templates/profile/profile.html
{% extends "base.html" %}
{% block content %}

<style>
.expert {
  border: 1px solid lightgray;
  padding: 0.4rem;
  margin: 0.2 rem;
  border-radius: 1rem;
  font-size: 0.8rem;
  color: gray;
}
</style>

<div class="profile">
  <p><b>Nama: </b>{{ user.nama }}</p>
  <p><b>NPM: </b>{{ user.npm }}</p>
  <p><b>Keahlian: </b>{% for ii in split_expertise %} <span class="expert">{{ ii }}</span> {% endfor %}</p>
  <p><b>Email: </b>{{ user.email }}</p>
  <p><b>Profile LinkedIn: </b>{{ user.url_linkedin}}</p>
</div>
{% endblock %}