cari/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$', index, name='index'),
]

linkensphere/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import profile.urls as profile
from profile.views import index as index_profile
from django.views.generic import TemplateView
import riwayat.urls as riwayat
import user_auth.urls as user_auth
import status_page.urls as status_page
import cari.urls as cari


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^profile/status/', include(status_page, namespace='status_page')),
    url(r'^$', TemplateView.as_view(template_name='landingPage.html'),name='landingpage'),
    url(r'^$', RedirectView.as_view(url='/profile/', permanent=True), name='index'),
    url(r'^riwayat/', include(riwayat, namespace='riwayat')),
    url(r'^user_auth/', include(user_auth, namespace='user_auth')),
	url(r'^profile/teman/', include(cari, namespace='cari'))

]
#url

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Linken's Sphere</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <script src="https://use.fontawesome.com/78a1390031.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous">
    </script>
    <style>
      .footer {
        margin: 1rem;
        font-family: 'Open Sans', sans-serif;
        font-weight: 400;
      }
    </style>
</head>
<body>
  <div class="gradientHeader"></div>
  <div class="mobileNavigation" id="mobileNavigation">
    <a href="/profile">Profile</a>
  </div>
  <div class="mainContainer">
    <div class="navigationBar">
      <div class="hamburgerIcon" id="hamburgerIcon" onclick="toggleIcon()">
        <div class="hamburgerIconTop"></div>
        <div class="hamburgerIconBottom"></div>
      </div>
      <div class="logo">LINKEN'S SPHERE</div>
      <div class="navigation">
        <a href="/profile">Profile</a>
      </div>
    </div>
    <div class="container">
      <div class="containerHeader">
        <div class="headerSection">
        </div>
        <div class="headerSection">
          <img class="headerPhoto" src="{{ user.foto }}"/>
        </div>
        <div class="headerSection editProfile">
          <a href="/profile/edit" class="editProfileButton">
            <i class="fa fa-pencil" aria-hidden="true"></i>
            EDIT
          </a>
        </div>
      </div>
      <div class="containerDescription">
        <h1>{{ user.nama }}</h1>
        <h2>{{ user.headline }}</h2>
        <div class="containerStatus">
          <span><h3>Status Count: {{ status_count }}</h3> </span>
          <span><h3>Current Status: {{ latest_status.message }}</h3></span>
       </div>
      </div>
      <div class="menuSelector">
        <button class="editProfileButton {% if menuSelected == 'profile' %} menuSelected{% endif %}"><a href="/profile"> Profile</a></button>
        <button class="editProfileButton {% if menuSelected == 'riwayat' %} menuSelected{% endif %}"><a href="/riwayat">Riwayat</a></button>
        <button class="editProfileButton {% if menuSelected == 'status' %} menuSelected{% endif %}"><a href="/profile/status">Status</a></button>
		<button class="editProfileButton {% if menuSelected == 'teman' %} menuSelected{% endif %}"><a href="/profile/teman">Teman</a></button>
      </div>
      <div class="containerContent">
        {% block content %}
        {% endblock %}
      </div>
    </div>
    <div class="footer">&copy; Made with love by: Irene, Atalya, Kevin, Yogi</div>
  </div>
<script>
  function toggleIcon() {
    if (document.getElementById("hamburgerIcon").className === "hamburgerIcon") {
      document.getElementById("hamburgerIcon").className = "hamburgerIconAfter";
      document.getElementById("mobileNavigation").className = "mobileNavigationShow";
    } else {
      document.getElementById("hamburgerIcon").className = "hamburgerIcon";
      document.getElementById("mobileNavigation").className = "mobileNavigation";
    }
  }
</script>
</body>
</html>

templates/basic.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Linken's Sphere</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <script src="https://use.fontawesome.com/78a1390031.js"></script>
    <style>
      .footer {
        margin: 1rem;
        font-family: 'Open Sans', sans-serif;
        font-weight: 400;
      }
    </style>
</head>
<body>
  <div class="gradientHeader"></div>
  <div class="mobileNavigation" id="mobileNavigation">
    <a href="/profile">Profile</a>
  </div>
  <div class="mainContainer">
    <div class="navigationBar">
      <div class="hamburgerIcon" id="hamburgerIcon" onclick="toggleIcon()">
        <div class="hamburgerIconTop"></div>
        <div class="hamburgerIconBottom"></div>
      </div>
      <div class="logo">LINKEN'S SPHERE</div>
      <div class="navigation">
        <a href="/profile">Profile</a>
      </div>
    </div>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <div class="footer">&copy; Made with love by: Irene, Atalya, Kevin, Yogi</div>    
  </div>
<script>
  function toggleIcon() {
    if (document.getElementById("hamburgerIcon").className === "hamburgerIcon") {
      document.getElementById("hamburgerIcon").className = "hamburgerIconAfter";
      document.getElementById("mobileNavigation").className = "mobileNavigationShow";
    } else {
      document.getElementById("hamburgerIcon").className = "hamburgerIcon";
      document.getElementById("mobileNavigation").className = "mobileNavigation";
    }
  }
</script>
</body>
</html>

templates/landingPage.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
		<title>Linken Sphere 2</title>
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
	</head>
	<style type="text/css">
		html, 
		body {
		    height: 100%;
		}
		body {
			margin: 0;
			font-family: 'Open Sans', sans-serif;
		}
		#particles-js {
			z-index: -100;
			background-image: linear-gradient(-20deg, #6e45e2 0%, #88d3ce 100%);
			height: 100%;
		}
		canvas {
			display: inline;
			vertical-align: bottom;
		}
		#appName {
			margin:0;
			color:white;
			font-weight: 300;
			font-size: 6em;
			white-space: nowrap;
		}
		.landingPageContent {
			position: absolute;
			top: 50%;
			left: 50%;
			transform: translate(-50%,-50%);
			text-align: center;
		}
		.button {
		  border-radius: 4px;
		  background-color: transparent;
		  border: none;
		  color: #FFFFFF;
		  text-align: center;
		  font-size: 28px;
		  padding: 20px;
		  width: 200px;
		  transition: all 0.5s;
		  cursor: pointer;
		  margin: 5px;
		  border: 3px solid white;
		}

		.button span {
		  cursor: pointer;
		  display: inline-block;
		  position: relative;
		  transition: 0.5s;
		}
		.button:hover{
			  background-color: #5C6BC0;

		}
		.button span:after {
		  content: '\00bb';
		  position: absolute;
		  opacity: 0;
		  top: 0;
		  right: -20px;
		  transition: 0.5s;
		}

		.button:hover span {
		  padding-right: 25px;
		}

		.button:hover span:after {
		  opacity: 1;
		  right: 0;
		}		

		h2 {
			color: white;
		}

	</style>
	<body>
		<div id="particles-js">
			<div class="landingPageContent">
				<h4 id="appName">LINKEN'S SPHERE</h4>
				<h2>Press button below to login with your SSO <span style="color:yellow">UI</span> account</h2>
				<a href="{% url 'user_auth:index'%}"><button class="button" ><span>LOGIN </span></button></a>
			</div>
		</div>


		<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
		<script type="text/javascript">
			particlesJS("particles-js", {
			  "particles": {
			    "number": {
			      "value": 150,
			      "density": {
			        "enable": true,
			        "value_area": 800
			      }
			    },
			    "color": {
			      "value": "#ffffff"
			    },
			    "shape": {
			      "type": "circle",
			      "stroke": {
			        "width": 0,
			        "color": "#000000"
			      },
			      "polygon": {
			        "nb_sides": 5
			      },
			      "image": {
			        "src": "img/github.svg",
			        "width": 100,
			        "height": 100
			      }
			    },
			    "opacity": {
			      "value": 0.5,
			      "random": false,
			      "anim": {
			        "enable": false,
			        "speed": 1,
			        "opacity_min": 0.1,
			        "sync": false
			      }
			    },
			    "size": {
			      "value": 3,
			      "random": true,
			      "anim": {
			        "enable": false,
			        "speed": 40,
			        "size_min": 0.1,
			        "sync": false
			      }
			    },
			    "line_linked": {
			      "enable": true,
			      "distance": 150,
			      "color": "#ffffff",
			      "opacity": 0.4,
			      "width": 1
			    },
			    "move": {
			      "enable": true,
			      "speed": 6,
			      "direction": "none",
			      "random": false,
			      "straight": false,
			      "out_mode": "out",
			      "bounce": false,
			      "attract": {
			        "enable": false,
			        "rotateX": 600,
			        "rotateY": 1200
			      }
			    }
			  },
			  "interactivity": {
			    "detect_on": "canvas",
			    "events": {
			      "onhover": {
			        "enable": true,
			        "mode": "grab"
			      },
			      "onclick": {
			        "enable": true,
			        "mode": "push"
			      },
			      "resize": true
			    },
			    "modes": {
			      "grab": {
			        "distance": 140,
			        "line_linked": {
			          "opacity": 1
			        }
			      },
			      "bubble": {
			        "distance": 400,
			        "size": 40,
			        "duration": 2,
			        "opacity": 8,
			        "speed": 3
			      },
			      "repulse": {
			        "distance": 200,
			        "duration": 0.4
			      },
			      "push": {
			        "particles_nb": 4
			      },
			      "remove": {
			        "particles_nb": 2
			      }
			    }
			  },
			  "retina_detect": true
			});



		</script>
	</body>
</html>